# Generated by Django 5.2.7 on 2025-11-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('add', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
