# Generated by Django 5.2.7 on 2025-11-19 04:21

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='items',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_item_name_case_insensitive', violation_error_message='Name must be unique (case-insensitive).'),
        ),
    ]
